### ISSUE TITLE
The icon for Firefox Monitor sometimes is not displayed

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-addon#110] opened 2018-08-30 09:42 UTC
[Affected versions]:

- Firefox 62.0
- Firefox 63.0a1

- Firefox Monitor 2.1

[Affected Platforms]:
- Windows 10 x64
- Windows 7 x64
- macOS 10.13
- Ubuntu 16.04 x64

[Prerequisites]:
Prefs you'll need to set in about:config:

- (boolean) extensions.fxmonitor.enabled - true
- (string) extensions.fxmonitor.breachListURL - https://haveibeenpwned.com/api/v2/breaches

[Steps to reproduce]:
1. Make sure that Firefox Monitor is enabled.
2. Restart browser.
3. Access in a new tab any of the sites from this list: https://docs.google.com/spreadsheets/d/1GYsLxXdCTlV5INzkpVBlpRPS3kfj-pTG7INOPSX6Up4/edit#gid=1389057478, but don't let it fully load (close the tab before the site fully loaded).
4. Access the same link from step 3 in a new tab.

[Expected result]:
- The icon on the doorhanger is displayed.

[Actual result]:
- The icon on the doorhanger is not displayed and if you try to open any other link from the list in the same window the icon is not displayed. 

[Regression]:
-I don't think this is a regression.

[Notes]:
- This happens at random times, too. This is the only way I could make it reproduce every time.  
- Please look at the attached gif.
![peek 2018-08-30 12-34](https://user-images.githubusercontent.com/42799381/44843541-349f8c80-ac51-11e8-85cb-f0e0d0c05dda.gif)

**Comment by nhnt11** [comment] 2018-08-30 12:53
@obotisan In the gif, you are disabling the addon. Is this part of the STR? Please note that disabling the addon was not handled correctly and a fix has been submitted in PR #108. If this is an issue caused by disabling the addon, it will probably be fixed by that PR.

**Comment by obotisan** [comment] 2018-08-30 13:54
Yes, I did. But I logged the issue because it happened in different circumstances, too. I only wrote those steps because using them the issue is reproducing all the time. 
We managed to reproduce the issue in other ways, but we didn't have clear steps for it. I thought that maybe it's a general issue and if you can fix this issue, it won't reproduce by using other steps.

**Comment by nhnt11** [comment] 2018-08-30 15:12
I don't have any ideas for how this could happen with #108 applied. The icon is set from code, not CSS, and the styling is done by existing browser styles, no custom styling is applied by the addon.

The only thing I can think of is, before #108, it would be possible that the icon asset is no longer available (if the addon is uninstalled for example) and therefore doesn't display. #108 should fix that.

**Comment by obotisan** [comment] 2018-08-31 12:33
We verify the fix using RC 62.0 -build 2 on Windows 10 x64, Ubuntu 16.04 x64 an Mac OS 10.11. The bug is not reproducing anymore.
I tried some different scenarios too, but I wasn't able to reproduce the issue.

**Closed** 2018-08-31 13:46 UTC
Labels: [QA]:Verified Fixed
