### ISSUE TITLE
Firefox Monitor study is still displayed in "about:addons" page after clicking the "Disable" or "Remove" buttons

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/blurts-addon#34] opened 2018-06-14 14:01 UTC
[Affected versions]:
- Firefox 60.0.2
- Firefox Monitor 0.01, All Branches

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a clean Firefox profile with the latest Firefox Monitor installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Go to "about:addons" page, "Extensions" section.
3. Click the "Disable" (or "Remove") button specific to the study and observe what happens next.

[Expected result]:
- The "Firefox Monitor" add-on is no longer displayed in "about:addons" page.

[Actual result]:
- The "Firefox Monitor" add-on is still displayed in "about:addons" page.

[Notes]:
- Here is a screen recording with this issue:
![firefox monitor - disable or remove](https://user-images.githubusercontent.com/31244235/41416823-686041e8-6ff4-11e8-8ad8-94b507fd5709.gif)

**Comment by pdehaan** [comment] 2018-06-14 20:32
I'm not sure this is a bug. Weird, definitely. Bug, ¯\\\_(ツ)\_/¯.
Note that if you remove the bug, and then REFRESH the page, it should disappear.
But I think the current behavior is just the way of the about:addons page.

**Comment by nhnt11** [comment] 2018-06-29 12:17
Yeah, I don't get it. The screen recording shows that you are clicking "undo" so isn't this expected?

**Comment by SoftVision-CarmenFat** [comment] 2018-06-29 12:24
Actually, shield studies should not be displayed anymore in "about:addons" page after the user disables/removes the experiment. The reasoning and other details about this behavior can be found in the email thread I've forwarded you yesterday.

**Comment by gregglind** [comment] 2018-06-29 16:06
(I don't know anything about this, but I don't think it has anything shield specific.  I would ask @aswan or an addons person.)

**Comment by nhnt11** [comment] 2018-06-29 17:07
Fixed by #87

**Comment by aswan** [comment] 2018-06-29 17:19
Urgh, if we want a different handling of disable/uninstall for shield studies, I think it would be better to address that in the addon manager rather than in individual extensions using techniques like the one in the associated PR...
An earlier comment references an email thread, are the details publicly available somewhere?

**Comment by SoftVision-CarmenFat** [comment] 2018-07-02 15:15
Tested this with the signed Breach Alerts add-on (v. 1.2) and the issue is no longer reproducible. Clicking the "Disable" and "Remove" buttons uninstalls the add-on and the experiment is no longer displayed in "about:addons" page.

**Closed** 2018-07-02 15:16 UTC
Labels: [QA]:Verified Fixed
